Creating test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
Operations to perform:
  Synchronize unmigrated apps: messages, rest_framework, staticfiles
  Apply all migrations: accounts, admin, auth, authtoken, contenttypes, orders, sessions
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying accounts.0001_initial... OK
  Applying accounts.0002_auto_20211125_2054... OK
  Applying orders.0001_initial... OK
  Applying accounts.0003_auto_20211130_1816... OK
  Applying accounts.0004_auto_20211130_1818... OK
  Applying accounts.0005_auto_20211130_1822... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying authtoken.0003_tokenproxy... OK
  Applying sessions.0001_initial... OK
System check identified no issues (0 silenced).
test_customer_fields (accounts.tests.tests_models.CustomerModelTest) ... ok
test_create_customer_fail_when_cpf_exists (accounts.tests.tests_views.CustomerViewTest) ... ok
test_create_customer_fail_when_missing_fields (accounts.tests.tests_views.CustomerViewTest) ... ok
test_create_new_customer (accounts.tests.tests_views.CustomerViewTest) ... ok
test_login_fail (accounts.tests.tests_views.LoginCustomerViewTest) ... ok
test_login_success (accounts.tests.tests_views.LoginCustomerViewTest) ... ok
test_login_fail (accounts.tests.tests_views.LoginPartnerViewTest) ... ok
test_login_success (accounts.tests.tests_views.LoginPartnerViewTest) ... ok
test_create_new_partner (accounts.tests.tests_views.PartnerViewTest) ... ok
test_create_partner_fail_when_missing_fields (accounts.tests.tests_views.PartnerViewTest) ... ok
test_create_user_fail_when_cpf_exists (accounts.tests.tests_views.PartnerViewTest) ... ok
test_a_customer_cannot_update_another_customer_data (accounts.tests.tests_views.SeachingAndUpdatingCustomerTest) ... ok
test_anonymous_cannot_search_for_a_specific_customer_by_id (accounts.tests.tests_views.SeachingAndUpdatingCustomerTest) ... ok
test_anyone_authenticated_can_search_for_a_specific_customer_by_id (accounts.tests.tests_views.SeachingAndUpdatingCustomerTest) ... ok
test_is_is_not_possible_to_search_for_a_customer_by_id_that_does_not_exist (accounts.tests.tests_views.SeachingAndUpdatingCustomerTest) ... ok
test_is_is_not_possible_to_update_a_customer_by_id_that_does_not_exist (accounts.tests.tests_views.SeachingAndUpdatingCustomerTest) ... ok
test_only_the_customer_himself_can_update_his_data (accounts.tests.tests_views.SeachingAndUpdatingCustomerTest) ... ok
test_a_partner_cannot_update_another_user_data (accounts.tests.tests_views.UpdatingPartnerTest) ... ok
test_is_is_not_possible_to_update_a_partner_by_id_that_does_not_exist (accounts.tests.tests_views.UpdatingPartnerTest) ... ok
test_only_the_partner_himself_can_update_his_data (accounts.tests.tests_views.UpdatingPartnerTest) ... ok
test_address_field_type (orders.tests.test_model.TestOrderModel) ... ok
test_address_field_value (orders.tests.test_model.TestOrderModel) ... ok
test_order_field_type (orders.tests.test_model.TestOrderModel) ... ok
test_order_field_value (orders.tests.test_model.TestOrderModel) ... ok
test_residence_field_type (orders.tests.test_model.TestOrderModel) ... ok
test_residence_field_value (orders.tests.test_model.TestOrderModel) ... ok
test_service_field_type (orders.tests.test_model.TestOrderModel) ... ok
test_service_field_value (orders.tests.test_model.TestOrderModel) ... ok
ERROR

======================================================================
ERROR: setUpClass (orders.tests.test_views.TestOrdersView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mcromao/kenzie/q4/sprint3/capstone/cleango-django/venv/lib/python3.9/site-packages/django/test/testcases.py", line 1201, in setUpClass
    cls.setUpTestData()
  File "/home/mcromao/kenzie/q4/sprint3/capstone/cleango-django/orders/tests/test_views.py", line 47, in setUpTestData
    cls.residence = ResidenceType.objects.create(dict(name='Casa'))
  File "/home/mcromao/kenzie/q4/sprint3/capstone/cleango-django/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
TypeError: create() takes 1 positional argument but 2 were given

----------------------------------------------------------------------
Ran 28 tests in 2.690s

FAILED (errors=1)
Destroying test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
